pkonly: true
lootingrate: 0.2
mobpkonly: true
fixcase: false
updatecheck: true
broadcast: true
broadcastrange: 0
broadcastmob: false
broadcastmobrange: 0
antideathchest: false
addlore: false


requireitem: false
requireditems: [wooden_axe,stone_axe,golden_axe,iron_axe,diamond_axe]

considermobkillers: false
considertameowner: false

#------mob rates------#

creeperdroprate: 0.005
zombiedroprate: 0.002
skeletondroprate: 0.002
witherskeletondroprate: 0.025
spiderdroprate: 0.002
endermandroprate: 0.002
blazedroprate: 0.002
horsedroprate: 0.002
donkeydroprate: 0.002
squiddroprate: 0.005
silverfishdroprate: 0.005
enderdragondroprate: 0.05
slimedroprate: 0.001
irongolemdroprate: 0.005
mushroomcowdroprate: 0.002
batdroprate: 0.005
pigzombiedroprate: 0.002
snowmandroprate: 0.002
ghastdroprate: 0.005
pigdroprate: 0.002
villagerdroprate: 0.002
sheepdroprate: 0.002
cowdroprate: 0.002
chickendroprate: 0.002
ocelotdroprate: 0.005
witchdroprate: 0.005
magmacubedroprate: 0.001
wolfdroprate: 0.002
cavespiderdroprate: 0.002
rabbitdroprate: 0.002
guardiandroprate: 0.025
elderguardiandroprate: 0.030
polarbeardroprate: 0.005
shulkerdroprate: 0.002
straydroprate: 0.002
endermitedroprate: 0.005
evokerdroprate: 0.005
illusionerdroprate: 0.005
vindicatordroprate: 0.005
witherdroprate: 0.005
vexdroprate: 0.004
llamadroprate: 0.008
parrotdroprate: 0.008

#new drop rates supported since the 4.x redesign
huskdroprate: 0.002
zombievillagerdroprate: 0.002
skeletonhorsedroprate: 0.002
zombiehorsedroprate: 0.002
muledroprate: 0.002
turtledroprate: 0.002
phantomdroprate: 0.001
coddroprate: 0.002
salmondroprate: 0.002
pufferfishdroprate: 0.002
tropicalfishdroprate: 0.002
drowneddroprate: 0.002
dolphindroprate: 0.002

#remaining living-entity entries - disabled by default
giantdroprate: 0.0
armorstanddroprate: 0.0

#speculative drop rates with 1.14 mobs - these names are NOT final
pillagerdroprate: 0.002
ravagerdroprate: 0.005
pandadroprate: 0.002
catdroprate: 0.002
foxdroprate: 0.002
traderllamadroprate: 0.005
wanderingtraderdroprate: 0.005

