name: MobEggDrops
version: ${project.version}
description: Drops a mob's egg when they die
authors: [crashdemons, meiskam, zand]

api-version: 1.13

main: org.shininet.bukkit.mobeggdrops.MobEggDrops
database: false

softdepend: [NoCheatPlus,BountyHunters]

commands:
  MobEggDrops:
    description: Spawn a mobegg or edit mobeggdrops config
    aliases: med

permissions:
  mobeggdrops.*:
    description: Gives all MobEggDrops permissions
    default: false
    children:
      mobeggdrops.config.*: true
      mobeggdrops.spawn.*: true
      mobeggdrops.update: true
      mobeggdrops.canberewarded: true
      mobeggdrops.update: true
      mobeggdrops.alwaysrewarded: true
      mobeggdrops.clickinfo: true
  mobeggdrops.config.*:
    description: Allows user to edit, save, or reload configs
    default: op
    children:
      mobeggdrops.config.get: true
      mobeggdrops.config.set: true
  mobeggdrops.config.get:
    description: Allows user to get configs
    default: op
  mobeggdrops.config.set:
    description: Allows user to set or reload configs
    default: op
  mobeggdrops.spawn.*:
    description: Spawn player eggs
    default: op
    children:
      mobeggdrops.spawn: true
      mobeggdrops.spawn.forother: true
  mobeggdrops.spawn:
    description: Spawn any player egg
    default: op
    children:
      mobeggdrops.spawn.own: true
  mobeggdrops.spawn.own:
    description: Spawn your own egg
    default: op
  mobeggdrops.spawn.forother:
    description: Spawn a egg into someone elses inventory
    default: op
  mobeggdrops.canberewarded:
    description: User can receive egg drops
    default: true
  mobeggdrops.update:
    description: When update available, can view notice and manually update
    default: op
  mobeggdrops.alwaysrewarded:
    description: Ignore drop rate for eggs and drop 100% of the time
    default: false

